---
# openvpn package
package: openvpn

# default interface
interface: tun0

# openvpn client variables
vpn_client:
  - family: RedHat
    service: openvpn-client@client
    config_path: /etc/openvpn/client

  - family: Debian
    service: openvpn@client
    config_path: /etc/openvpn

  - family: Suse
    service: openvpn@client
    config_path: /etc/openvpn

# authorized vpn user credentials
auth:
  - user: <username>
  - pass: <password>

# location variable
location: usa-sanfrancisco
#location: hongkong-1
#location: uk-london
